# Generated by Django 3.1.6 on 2021-06-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
