# Generated by Django 3.0.7 on 2020-11-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
